version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
    ports: 
      - "8082:80"
    networks:
      - internal
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    depends_on:
        mysqldb:
            condition: service_started
            
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
            - mysqldb
    networks:
      - internal

  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8083:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb

  mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8084:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
networks:
  internal:
    driver: bridge
